package de.upb.cs.config;

public enum Message {
    NONE,
    INITIAL_CLIENT_HELLO,
    CLIENT_HELLO,
    RSA_CLIENT_KEY_EXCHANGE,
    DH_CLIENT_KEY_EXCHANGE,
    ECDH_CLIENT_KEY_EXCHANGE,
    SERVER_HELLO,
    DH_SERVER_KEY_EXCHANGE,
    ECDH_SERVER_KEY_EXCHANGE,
}
