package de.upb.cs.config;

public enum OverlappingField {
    NO_FIELD,
    CLIENT_HELLO,
    CLIENT_HELLO_VERSION,
    CLIENT_HELLO_CIPHER_SUITE,
    CLIENT_HELLO_EXTENSION,
    CLIENT_KEY_EXCHANGE,
    CLIENT_KEY_EXCHANGE_RSA,
    CLIENT_KEY_EXCHANGE_DH,
    CLIENT_KEY_EXCHANGE_ECDH,
    SERVER_HELLO,
    SERVER_HELLO_VERSION,
    SERVER_HELLO_CIPHER_SUITE,
    SERVER_KEY_EXCHANGE,
    SERVER_KEY_EXCHANGE_DH,
    SERVER_KEY_EXCHANGE_ECDH,
}
